# Generated by Django 6.0.5 on 2026-06-03 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('color', models.CharField(default='#6C63FF', max_length=7, verbose_name='Колір')),
                ('icon', models.CharField(default='✅', max_length=10, verbose_name='Іконка')),
                ('frequency', models.CharField(choices=[('daily', 'Щодня'), ('weekly', 'Щотижня'), ('custom', 'Вибрані дні')], default='daily', max_length=10, verbose_name='Частота')),
                ('target_days', models.JSONField(default=list, verbose_name='Цільові дні тижня')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Звичка',
                'verbose_name_plural': 'Звички',
                'ordering': ['-created_at'],
            },
        ),
    ]
