# Generated by Django 6.0.5 on 2026-06-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Звичка', 'verbose_name_plural': 'Звички'},
        ),
        migrations.AddField(
            model_name='habit',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
