# Generated by Django 6.0.5 on 2026-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcheckin',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
    ]
